import React from 'react';
import Layout from '../components_en/Layout';

const PrivacyPolicy = () => {
  return (
    <Layout>
      <div className="bg-white min-h-screen flex-grow">
      <div className="max-w-8xl mx-auto px-4 3xl:px-8 4xl:px-12 5xl:px-16 pt-32 3xl:pt-40 4xl:pt-48 pb-12 3xl:pb-16 4xl:pb-20">
        <h1 className="text-3xl 3xl:text-4xl 4xl:text-5xl 5xl:text-6xl font-bold mb-8 3xl:mb-12 4xl:mb-16">Privacy Policy</h1>
        <div className="space-y-6 3xl:space-y-8 4xl:space-y-10 text-gray-700 text-base 3xl:text-lg 4xl:text-xl 5xl:text-2xl leading-relaxed">

          {/* User Information to be Acquired */}
          <section>
            <h2 className="text-xl 3xl:text-2xl 4xl:text-3xl 5xl:text-4xl font-semibold mb-4 3xl:mb-6 4xl:mb-8">User Information to be Acquired</h2>
            <p>
              the Company may acquire from the user(s) (the "User(s)) the following information (the "User Information"):
            </p>
            <ul className="list-disc ml-6 3xl:ml-8 4xl:ml-10 mt-4 3xl:mt-6 4xl:mt-8 space-y-2 3xl:space-y-3 4xl:space-y-4">
              <li>Location information of the Users</li>
              <li>Name (including nicknames and pen names)</li>
              <li>E-mail address</li>
              <li>Identification information generated by using cookies</li>
              <li>Information regarding the OS and the terminal used by the User, such as ID generated by the OS, the type of the terminal, and the terminal identifier</li>
              <li>History of the Users' activities on the Company's website, such as time spent on the Company's website, input history, and purchase history</li>
            </ul>
          </section>

          <hr className="border-gray-300" />

          {/* Purpose of Use of User Information */}
          <section>
            <h2 className="text-xl 3xl:text-2xl 4xl:text-3xl 5xl:text-4xl font-semibold mb-4 3xl:mb-6 4xl:mb-8">Purpose of Use of User Information</h2>
            <p>The Company uses User information for the following purpose:</p>
            <ul className="list-disc ml-6 3xl:ml-8 4xl:ml-10 mt-4 3xl:mt-6 4xl:mt-8 space-y-2 3xl:space-y-3 4xl:space-y-4">
              <li>to register or verify the User's identity and authenticate with the Company's services (the "Services")</li>
              <li>to manage the User's usage history of the Services</li>
              <li>to settle usage fees</li>
              <li>to analyze the User's activity history in the Services to maintain and improve the Services</li>
              <li>for market analysis and marketing</li>
              <li>to inform the User of the Services</li>
              <li>to respond to the User's inquiries</li>
              <li>to correspond to actions that violate the Company's terms and conditions, laws and regulations</li>
              <li>to inform the User of changes to, discontinuance of, termination of, or cancellation of the Services</li>
              <li>to inform the changes etc. to the Company's terms and conditions</li>
              <li>any other act to provide, maintain, protect and improve the Services</li>
              <li>to distribute, display and measure the effectiveness of advertisements</li>
              <li>to display targeted advertisements tailored to the User's interests and preferences</li>
              <li>to analyze search queries and search history to improve the Services</li>
              <li>to manage and analyze the click history of search results</li>
              <li>to analyze the usage time and frequency of the search services to optimize performance and user experience</li>
            </ul>
          </section>

          <hr className="border-gray-300" />

          {/* Third Party Provision */}
          <section>
            <h2 className="text-xl 3xl:text-2xl 4xl:text-3xl 5xl:text-4xl font-semibold mb-4 3xl:mb-6 4xl:mb-8">Third Party Provision</h2>
            <p>
              The Company will not provide any information collected from the Users that constitutes personal data (Article 2, Paragraph (6) of Act on the Protection of Personal Information) to any third party (including anyone outside Japan) without obtaining in advance the Users' consent. However, this shall not apply in the following cases:
            </p>
            <ul className="list-disc ml-6 3xl:ml-8 4xl:ml-10 mt-4 3xl:mt-6 4xl:mt-8 space-y-2 3xl:space-y-3 4xl:space-y-4">
              <li>if the Company outsource the handling of personal data</li>
              <li>if the Company or the Services are acquired</li>
              <li>if the Company jointly use personal data with its business partner (if there is a specific joint use, the details will be announced separately.)</li>
              <li>any other cases in which provision of personal data to a third party is permitted by law</li>
            </ul>
          </section>

          <hr className="border-gray-300" />

          {/* Access Analysis Tools */}
          <section>
            <h2 className="text-xl 3xl:text-2xl 4xl:text-3xl 5xl:text-4xl font-semibold mb-4 3xl:mb-6 4xl:mb-8">Access Analysis Tools</h2>
            <p>
              The Company uses "Google Analytics" to analyze the User's access. Google Analytics uses cookies to collect traffic data. Traffic data is collected anonymously and is not personally identifiable. By disabling cookies, the User can refuse collection of these information. Please check your browser settings for details. To learn more about Google Analytics, visit: <a href="https://marketingplatform.google.com/about/analytics/terms/jp/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">https://marketingplatform.google.com/about/analytics/terms/jp/</a>
            </p>
          </section>

          <hr className="border-gray-300" />

          {/* Distribution of Advertisements */}
          <section>
            <h2 className="text-xl 3xl:text-2xl 4xl:text-3xl 5xl:text-4xl font-semibold mb-4 3xl:mb-6 4xl:mb-8">Distribution of Advertisements</h2>
            <p>
              The Company places advertisements provided by Google and its partner ("Third Party Distributors"). Cookies are used to serve advertisements and serve advertisements based on information that the User has visited the Company's website and other websites in the past. Google and its partner use cookies to ensure that appropriate advertisements are displayed. The User may disable personalized advertisements from the User's Google Account Ad Settings page at: <a href="https://adssettings.google.com/u/0/authenticated" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">https://adssettings.google.com/u/0/authenticated</a> The User can also visit aboutads.info to disable Third Party Distributors' cookies used to place personalized advertisements. For more information on Google's handling of cookies, please visit Google's policy and terms page at: <a href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">https://policies.google.com/technologies/ads</a>
            </p>
            <p className="mt-4 3xl:mt-6 4xl:mt-8">
              The Company participates in the following affiliate programs. As a result, third parties may provide contents and advertisements, collect information directly from visitors, and place or recognize cookies in visitors' browsers. By disabling cookies, the User may refuse collection of these information. Please check your browser settings for details.
            </p>
            <ul className="list-disc ml-6 3xl:ml-8 4xl:ml-10 mt-4 3xl:mt-6 4xl:mt-8 space-y-2 3xl:space-y-3 4xl:space-y-4">
              <li>
                <strong>A8.net</strong> (Fan Communications Inc.)
              </li>
              <li>
                <strong>AccessTrade</strong> (Interspace Co., Ltd.)<br />
                Details: <a href="https://www.accesstrade.ne.jp" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">https://www.accesstrade.ne.jp</a>
              </li>
            </ul>
          </section>

          <hr className="border-gray-300" />

          {/* Anonymously Processed Information */}
          <section>
            <h2 className="text-xl 3xl:text-2xl 4xl:text-3xl 5xl:text-4xl font-semibold mb-4 3xl:mb-6 4xl:mb-8">Anonymously Processed Information</h2>
            <p>
              The Company may produce and use anonymously processed information (this means those set forth in Article 2, paragraph (9) of Act on the Protection of Personal Information, and limited to those constituting anonymously processed information database etc. set forth in Article 2, paragraph (10) of the said Act) by using information acquired from the Users. In such case, the Company will take actions as required by Act on the Protection of Personal Information.
            </p>
          </section>

          <hr className="border-gray-300" />

          {/* Amendment to Privacy Policy */}
          <section>
            <h2 className="text-xl 3xl:text-2xl 4xl:text-3xl 5xl:text-4xl font-semibold mb-4 3xl:mb-6 4xl:mb-8">Amendment to Privacy Policy</h2>
            <p>
              The Company will amend this Privacy Policy as necessary. In such case, the Company will announce or notify, in an appropriate manner, the timing when the amended Privacy Policy will be enforced and the contents thereof.
            </p>
          </section>

          <hr className="border-gray-300" />

          {/* Contact Information */}
          <section>
            <h2 className="text-xl 3xl:text-2xl 4xl:text-3xl 5xl:text-4xl font-semibold mb-4 3xl:mb-6 4xl:mb-8">Contact Information</h2>
            <p>
              If you wish to disclose, correct, suspend use of or delete your information, please contact us at the following email address.
            </p>
            <p className="mt-4 3xl:mt-6 4xl:mt-8">
              <strong>Email</strong>: <a href="mailto:8xaidcircles@gmail.com" className="text-blue-600 hover:underline">8xaidcircles@gmail.com</a>
            </p>
            <p className="mt-4 3xl:mt-6 4xl:mt-8">
              In such a case, we will confirm that such request was made by the person himself/herself, by asking such person to present his/her driver's license or by other means designated by the Company. Requests for disclosure of information, whether such information will be disclosed or not, are subject to a processing fee of 1,000 yen per case at the time of application.
            </p>
          </section>

          <hr className="border-gray-300" />

          {/* Company name */}
          <section>
            <h2 className="text-xl 3xl:text-2xl 4xl:text-3xl 5xl:text-4xl font-semibold mb-4 3xl:mb-6 4xl:mb-8">Company name</h2>
            <p>
              <strong>8X Aid Circles</strong>
            </p>
          </section>

          <hr className="border-gray-300" />

          {/* Translation Notice */}
          <section>
            <p>
              The original version of these Terms (and Privacy Policy) is in Japanese.
            </p>
            <p className="mt-2 3xl:mt-4 4xl:mt-6">
              The English translation is provided for reference only.
            </p>
            <p className="mt-2 3xl:mt-4 4xl:mt-6">
              In the event of any inconsistency, the Japanese version shall prevail.
            </p>
          </section>

          <hr className="border-gray-300" />

          {/* Prescribed Date */}
          <section className="mt-8 3xl:mt-12 4xl:mt-16">
            <p><strong>Prescribed on</strong>: November 29, 2025</p>
          </section>

        </div>
      </div>
      </div>
    </Layout>
  );
};

export default PrivacyPolicy;
